name: Deploy em Produção
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Sincronizar arquivos com a pasta do projeto
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' ./ /home/totem-software/api-dados

      - name: Build
        run: |
          cd /home/totem-software/api-dados
          npm install
          npm run build
      
      - name: Deploy
        run: |
          cd /home/totem-software/api-dados
          pm2 restart superapp --update-env
      