name: Deploy to DigitalOcean

on:
  push:
    branches:
      [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-actions@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/api-dados
            git pull origin main
            npm install
            npm run build:clean
            pm2 reload api-dados --update-env
            echo "Deploy finalizado com sucesso!"