name: Deploy to DigitalOcean

on:
  push:
    branches:
      [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-actions@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "=== Iniciando deploy ==="
            cd /root/api-dados
            git pull origin main

            echo "=== Instalando dependências ==="
            npm install

            echo "=== Fazendo build ==="
            npm run build:clean

            echo "=== Reiniciando aplicação com PM2 ==="
            pm2 reload api-dados --update-env || pm2 start dist/index.js --name app-teste
            
            echo "Deploy finalizado com sucesso!"